version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  public_spree:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/estiTasker
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /estiTasker/log
      - /estiTasker/tmp
      - vendor_bundle:/estiTasker/vendor/bundle
      - node_modules:/estiTasker/node_modules
      - public_spree:/estiTasker/public/spree
      - storage:/estiTasker/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
